"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_blue)\
$directory\
[](fg:color_blue bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_bg2)\
$time\
[ ](fg:color_bg2)\
$line_break$character"""

palette = 'zenburn'

[palettes.zenburn]
color_fg0 = '#dcdccc'
color_bg1 = '#3f3f3f'
color_bg2 = '#4f4f4f'
color_bg3 = '#5f5f5f'
color_blue = '#6ca0a3'
color_aqua = '#5f8f5f'
color_green = '#5f8f5f'
color_orange = '#ac7373'
color_purple = '#b87898'
color_red = '#ac7373'
color_yellow = '#b87898'

[directory]
style = "fg:color_fg0 bg:color_blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'
staged = '+'
modified = '~'
untracked = '?'
deleted = '-'
renamed = '»'
conflicted = '='
ahead = '⇡'
behind = '⇣'
diverged = '⇕'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg2"
format = '[[  $time ](fg:color_fg0 bg:color_bg2)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
