#!bash

# Common aliases
alias c="clear"
alias ct="cleartool"
alias h="history"
alias where="which -a"

# Parallel build aliases
jobs=$(expr `cat /proc/cpuinfo | grep processor | wc -l` \* 2)
alias make="make -j$jobs"
alias scons="scons -j$jobs"
unset jobs

# vim: et:sw=4:ts=4
