#!zsh

# Graphical code review function
code_review () {
    /ccshare/linux/cc_tools/cr_review /ccshare/linux/c_spec/*cr$1*;
    ./cr_sh
}

# Code review function
code_review_pr () {
    /ccshare/linux/cc_tools/cr_review /ccshare/linux/c_spec/*cr$1*;
    sed -e 's/-gra//g' cr_sh > cr_sh1
    chmod 777 ./cr_sh1
    ./cr_sh1
}

# ClearCase prompt setup (strip ${USER}_ from $CLEARCASE_ROOT)
if [[ -n "$CLEARCASE_ROOT" ]]; then
    PS1_CLEARCASE="%{$reset_color%}[%{$fg[red]%}$(echo $CLEARCASE_ROOT | awk -F_ '{ print $NF }')%{$reset_color%}]"
    umask 002
fi

# Hostname prompt setup (strip "linux-pc-" from hostname)
PS1_HOSTNAME="%{$fg[yellow]%}$(hostname -s | awk -F- '{ print $NF }')"

# Update prompt
PS1='%{$fg[green]%}%n%{$reset_color%}@%{$fg[yellow]%}${PS1_HOSTNAME}${PS1_CLEARCASE}%{$reset_color%}${vcs_info_msg_0_}%{$reset_color%}> '

# Update paths
GNOME=3.10
QT=5.2.0
LLVM=3.3
DIRECTFB=1.7.1
PATH="$HOME/.local/bin:$HOME/.local/gnome-$GNOME/bin:$HOME/.local/qt-$QT/bin:$HOME/.local/llvm-$LLVM/bin:$HOME/.local/directfb-$DIRECTFB/bin:$HOME/src/hg/go/bin:$HOME/.local/rust/bin:$PATH:/usr/sbin"
PKG_CONFIG_PATH="$HOME/.local/lib/pkgconfig:$HOME/.local/gnome-$GNOME/lib/pkgconfig:$HOME/.local/qt-$QT/lib/pkgconfig:$HOME/.local/llvm-$LLVM/lib/pkgconfig:$HOME/.local/directfb-$DIRECTFB/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig"

# Aliases
alias ct="LD_LIBRARY_PATH=/lib:/usr/lib cleartool"
