#!zsh

#if test -e /opt/rh/devtoolset-4/enable; then
#    . /opt/rh/devtoolset-4/enable
#fi

#if test -e /opt/exegy/llvm-8/enable; then
#    . /opt/exegy/llvm-8/enable
#fi

if test -e /opt/rh/python27/enable; then
    . /opt/rh/python27/enable
fi

if command -v lsb_release &>/dev/null; then
    vendor=$(lsb_release -is)
    platform=${vendor%% *}-$(lsb_release -rs)
fi

PLATFORM=$HOME/.local/$platform

alias tree="tree -A"
