#!zsh

# Graphical code review function
code_review () {
    /ccshare/linux/cc_tools/cr_review /ccshare/linux/c_spec/*cr$1*;
    ./cr_sh
}

# Code review function
code_review_pr () {
    /ccshare/linux/cc_tools/cr_review /ccshare/linux/c_spec/*cr$1*;
    sed -e 's/-gra//g' cr_sh > cr_sh1
    chmod 777 ./cr_sh1
    ./cr_sh1
}

# ClearCase prompt setup (strip ${USER}_ from $CLEARCASE_ROOT)
if [[ -n "$CLEARCASE_ROOT" ]]; then
    PS1_CLEARCASE="%{$reset_color%}[%{$fg[red]%}$(echo $CLEARCASE_ROOT | awk -F_ '{ print $NF }')%{$reset_color%}]"
    umask 002
fi

# Hostname prompt setup (strip "linux-pc-" from hostname)
PS1_HOSTNAME="%{$fg[yellow]%}$(hostname -s | awk -F- '{ print $NF }')"

# Update prompt
PS1='%{$fg[green]%}%n%{$reset_color%}@%{$fg[yellow]%}${PS1_HOSTNAME}${PS1_CLEARCASE}%{$reset_color%}${vcs_info_msg_0_}%{$reset_color%}> '

# Update paths
PATH="$HOME/.local/bin:$HOME/.local/gnome-3.10/bin:$HOME/.local/qt-5.2.0/bin:$HOME/.local/llvm-3.3/bin:$PATH:/usr/sbin"
PKG_CONFIG_PATH="$HOME/.local/lib/pkgconfig:$HOME/.local/gnome-3.10/lib/pkgconfig:$HOME/.local/qt-5.2.0/lib/pkgconfig:$HOME/.local/llvm-3.3/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig"

# Aliases
alias ct=cleartool
