vim_mode = true

[ai]
endpoint = "https://ai.drwcloud.com/v1"
endpoint_protocol = "oss"

[search]
search_mode = "fuzzy"

[ui]
style = "compact"

[history]
filter_mode = "global"
filter_mode_shell_up_arrow = "directory"
